### ISSUE TITLE
npm start fails since second commit 

### ISSUE THREAD

**Issue by cob16** [HLPugs/Payload#1]
It seems the commit that removes all the css files has broken the project 1d2873c38456f4ae3ee1c112a6bf4dde764e2c75

**Comment by Nicell** [comment]
This is correct. You need to build the .css files using `npm run build-css` before running for the first time. When working with the .scss files, you should also probably have use `npm run watch-css`. I should be writing up the readme soon to better explain this. Perhaps adding `build-css` to the `start` script is a good idea.
